# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=180, verbose_name='Descrição')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaMateria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade Utilizada')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisprod.Etapa', verbose_name='Etapa')),
            ],
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('quantidadeEstoque', models.IntegerField(verbose_name='Quantidade em Estoque')),
                ('custoAquisicao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='E-Mail')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsisprod.Cargo', verbose_name='Cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('dataInicio', models.DateTimeField(verbose_name='Data de Início')),
                ('dataTermino', models.DateTimeField(verbose_name='Data de Término')),
                ('prestadores', models.ManyToManyField(to='appsisprod.PrestadorServico', verbose_name='Prestadores')),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsisprod.Unidade', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='etapamateria',
            name='materiaPrima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appsisprod.MateriaPrima', verbose_name='Matéria Prima'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='materiasprimas',
            field=models.ManyToManyField(through='appsisprod.EtapaMateria', to='appsisprod.MateriaPrima', verbose_name='Matérias'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appsisprod.Processo', verbose_name='Processo'),
        ),
    ]
